version: "3"
services:
  php:
    build: 
      context: ./php
    networks:
      - frontend
      - backend
    environment:
      - MYSQL_HOST=docker-mysql
      - MYSQL_USER=user
      - MYSQL_PASSWORD=password
      - MYSQL_DB=docker_db
    volumes:
      - ./php:/var/www/html/
    ports:
      - "3001:80"
    container_name: docker-php
  mysql:
    image: mysql:5.7
    networks:
      - backend
    environment:
      - MYSQL_ROOT_PASSWORD=password
      - MYSQL_USER=user
      - MYSQL_PASSWORD=password
      - MYSQL_DATABASE=docker_db
    container_name: docker-mysql
  phpmyadmin:
    image: phpmyadmin/phpmyadmin:4.7
    depends_on:
      - mysql
    networks:
      - backend
    ports:
      - "3002:80"
    environment:
      - PMA_HOST=docker-mysql
      - PMA_PORT= 3306
    volumes:
      - /sessions
    container_name: docker-phpmyadmin
networks:
  frontend:
  backend:
